package Model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class UserModel {
    private Map<String, Object> user;

    /**
     * Constructor
     */
    public UserModel() {
        this.user = new HashMap<>();
    }
    
    public int createUser(String id, String firstName, String middleName, String lastName, int age, char gender, String phone, long zip){
        
        UserTable usr = new UserTable();

        usr.setId(id);
        usr.setFirstName(firstName);
        usr.setMiddleName(middleName);
        usr.setLastName(lastName);
        usr.setAge(age);
        usr.setGender(gender);
        usr.setPhone(phone);
        usr.setZip(zip);
        user.put(id, usr);
    
        return 1;
    }
    
    /**
     * Check to find if a user is available
     * @param id
     * @return
     */
    public boolean checkUser(String id) {
        Iterator it = user.entrySet().iterator();
        while (it.hasNext()) {
            Map.Entry pair = (Map.Entry)it.next();
            UserTable u = (UserTable)pair.getValue();
            if((u.getId().equals(id)))
                return false;
        }
        return true;
    }
    
    public int updateUser(String id, String firstName, String middleName, String lastName, int age, char gender, String phone, long zip){

        UserTable usr = (UserTable)user.get(id);

        usr.setFirstName(firstName);
        usr.setMiddleName(middleName);
        usr.setLastName(lastName);
        usr.setAge(age);
        usr.setGender(gender);
        usr.setPhone(phone);
        usr.setZip(zip);
        user.put(id, usr);
    
        return 1;
    }
    
    public boolean removeUser(String id) {
        if(!checkUser(id)) {
            user.remove(id);
            return true;    
        }
        return false;
    }
    public List sendElements() {
        List<Object> ret = new ArrayList<>(user.values());
        return ret;
    }

    public List sendUsersId() {
        List<Object> ret = new ArrayList<>(user.keySet());
        return ret;
    }

} // Class generated by : GitHub Coder
