package Model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class Model {
    private Map<String, Object> user;

    /**
     * Constructor
     */
    public Model() {
        this.user = new HashMap<>();
    }
    
    public int createUser(String id, String firstName, String lastName, int age, char gender, String phone, String middleName, long zip){

        UserTable usr = new UserTable();

        usr.setId(id);
        usr.setFirstName(firstName);
        usr.setLastName(lastName);
        usr.setAge(age);
        usr.setGender(gender);
        usr.setPhone(phone);
        usr.setMiddleName(middleName);
        usr.setZip(zip);
        user.put(id, user);
    
        return 1;
    }
    
    public int updateUser(String id, String firstName, String lastName, int age, char gender, String phone, String middleName, long zip){

        UserTable usr = (UserTable)user.get(id);

        usr.setFirstName(firstName);
        usr.setLastName(lastName);
        usr.setAge(age);
        usr.setGender(gender);
        usr.setPhone(phone);
        usr.setMiddleName(middleName);
        usr.setZip(zip);
        user.put(id, user);
    
        return 1;
    }

    public List sendElements() {
        List<Object> ret = new ArrayList<>(user.values());
        return ret;
    }

    public List send() {
        List<Object> ret = new ArrayList<>(user.keySet());
        return ret;
    }

} // Class generated by : GitHub Coder
