package User;
    
public class User{    
    
    private String id;
    private String firstName;
    private String lastName;
    private int age;
    private char gender;
    private String phone;
    private String middleName;
    private long zip;
    
    private String getId() {
        return id;
    }
    
    private void setId() {
        this.id = id;
    }
    
    private String getFirstName() {
        return firstName;
    }
    
    private void setFirstName() {
        this.firstName = firstName;
    }
    
    private String getLastName() {
        return lastName;
    }
    
    private void setLastName() {
        this.lastName = lastName;
    }
    
    private int getAge() {
        return age;
    }
    
    private void setAge() {
        this.age = age;
    }
    
    private char getGender() {
        return gender;
    }
    
    private void setGender() {
        this.gender = gender;
    }
    
    private String getPhone() {
        return phone;
    }
    
    private void setPhone() {
        this.phone = phone;
    }
    
    private String getMiddleName() {
        return middleName;
    }
    
    private void setMiddleName() {
        this.middleName = middleName;
    }
    
    private long getZip() {
        return zip;
    }
    
    private void setZip() {
        this.zip = zip;
    }
    
    @Override
    public boolean isValid() {
        
        // TODO : CODE THIS!
        return true;
    }
    
} // Class generated by : GitHub Coder
